menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}

people:
- {name: 'Citizen TV', title: 'Citizen', phone: ' +254 719 060 000', email: 'digitalsales@royalmedia.co.ke', image: 'assets/img/Citizen.png', url: 'https://www.citizen.digital/'}
- {name: 'NTV', title: 'NTV', phone: '+254 20 3288095', email: 'ntvsupport@ke.nationmedia.com', image: 'assets/img/ntv.png', url: 'https://ntvkenya.co.ke/'}
- {name: 'KTN', title: 'KTN', phone: '+254 719 012 111', email: 'customercare@ke.nationmedia.com', image: 'assets/img/KTN.png', url: 'https://www.standardmedia.co.ke/'}

social:
- {icon: 'github', link: 'https://github.com/yrncollo'}
- {icon: 'twitter', link: 'https://twitter.com/Yrn_Collo'}

